<?php include "media/header_footer_general/header.phtml"; ?>

	<?php header("Refresh: 5; URL=/index/index"); ?>
           
	<table border="0" align="center">
	  <tr>
		<td align="center"><img src="/media/images/<?php echo $this->imageIcon; ?>"></td>
	  </tr>
	  <tr>
		<td class="activateMessage"><?php echo $this->message; ?></td>
	  </tr>
	</table>

<?php include "media/header_footer_general/footer.phtml"; ?>
 
		    