<?php include "media/header_footer_general/header.phtml"; ?>

          <table border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
              <td colspan="3"><div align="justify" class="aboutDescription">Welcome to our site! We are Sourov and Rhythm from the Computer Science &amp; Engineering(CSE) department of BUET. Now we are at level-3, term-2. We developed this system as our term project for CSE 324 course under the supervision of Md. Abu Sayed Mondol Sir, Assistant Professor of CSE, BUET. </div></td>
            </tr>
            <tr>
              <td colspan="3">&nbsp;</td>
            </tr>
            <tr class="aboutImageDescription">
              <td width="400" align="center">
              	<img src="/media/images/sourov_pro_pic.JPG" border="1">Sourov on his way of Keokaradong
              </td>
              <td width="5">&nbsp;</td>
              <td width="400" align="center">
              	<img src="/media/images/rhythm_pro_pic.jpg" border="1">Rhythm at Birulia on a drizzling day		
              </td>
            </tr>
          </table>
        
<?php include "media/header_footer_general/footer.phtml"; ?>
