<?php include "media/header_footer_general/header.phtml"; ?>

    <table border="0" align="center" class="downloadDescription">
      <tr>
        <td colspan="3"><img border="1" src="/media/images/android_application.jpg"/></td>
      </tr>
      <tr>
        <td width="140">Application name:</td>
        <td width="150">CMS.apk</td>
        <td rowspan="4" align="right"><a href="/media/android_application/CMS.apk"><img src="/media/images/download.jpg"/></a></td>
      </tr>
      <tr>
        <td>Version:</td>
        <td>1.0</td>
      </tr>
      <tr>
        <td>Release date:</td>
        <td>10 October, 2012</td>
      </tr>
    </table>
    
<?php include "media/header_footer_general/footer.phtml"; ?>
