<?php include "media/header_footer_general/header.phtml"; ?>

    <table border="0" align="center" class="feedbackDescription">
      <tr>
        <?php 
			if ($this->form)
			{
				?>
                <td width="350" rowspan="8" class="feedbackFormDescription"> 
					<?php echo $this->form; ?> 
                </td>
				<?php
            }
			else
			{
				header("Refresh: 3; URL=/index/index");
				?>
                <td width="350" rowspan="8"> 
					<table border="0" align="center" class="feedbackMessage">
                      <tr>
                        <td align="center"><img src="/media/images/thanks.png"></td>
                      </tr>
                      <tr>
                        <td>Thank you for your feedback!</td>
                      </tr>
                    </table>
				</td>
				<?php
            }
		?>
        <td width="50" rowspan="8">&nbsp;</td>
        <td width="64" rowspan="4"><img src="/media/images/phone_contact.png"/></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>01722162249</td>
      </tr>
      <tr>
        <td>01716451393</td>
      </tr>
      <tr>
        <td width="206">&nbsp;</td>
      </tr>
      <tr>
        <td rowspan="4"><img src="/media/images/email_contact.png"/></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>sourov0805045@gmail.com</td>
      </tr>
      <tr>
        <td>rhythm.cse.buet@gmail.com</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table>
       
<?php include "media/header_footer_general/footer.phtml"; ?>
