<?php 
	include "media/header_footer_user/header.phtml"; 
	header("Refresh: 120; URL=/user/home"); //auto refresh after every 2 minutes
?>
	
  <tr>
    <td>
      <!--User's information here-->
      
        <table border="0" align="center" class="homeDescription">
          <tr>
            <td width="152" rowspan="5"><img name="" src="<?php echo $this->proPicLocation; ?>" alt="no image" width="150" height="150" border="1" /></td>
            <td width="30" rowspan="5">&nbsp;</td>
            <td width="80">Fullname:</td>
            <td width="300"><?php echo $this->datas['full_name']; ?></td>
          </tr>
          <tr>
            <td>Email:</td>
            <td><?php echo $this->datas['email']; ?></td>
          </tr>
          <tr>
            <td>Address:</td>
            <td><?php echo $this->datas['address']; ?></td>
          </tr>
          <tr>
            <td>Mobile no:</td>
            <td><?php echo $this->datas['mobile_no']; ?></td>
          </tr>
          <tr>
            <td height="30">&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
        </table>      
      
    </td>
    <td width="220" class="homeMenuMessage" align="center">
    <?php 
    	if ($this->form)
		{
			echo $this->form;
		}
		else
		{
			echo 'You have no child to select<br>Please <a href="/user/add-child">add a child</a> before!';	
		}
	?>
    </td>
  </tr>
  	<?php
		if (!isset($_SESSION['child_id']))
		{
			if ($this->form)
			{
			?>
                <tr>
                    <td colspan="2" align="center" height="20" class="homeSelectChildMessage">
                    	You need to select a child first!	
                    </td>
                </tr>
                <?php
            }
		}
		else
		{
		?>
			<tr>
				<td colspan=2>
					<p class="userTableHeader" align="center"> - - Data for <?php echo $_SESSION['child_name']; ?> - - </p>
				</td>
			</tr>
			<tr>
				<td colspan=2 height="30">
				</td>
			</tr>
    		<tr>
            	<td colspan="2" align="center">
            		
					<p class="userTableHeader">Location tracker</p>
					
                    <!-- map code starts here -->
                    
                    <table border="0" align="center" cellpadding="0" cellspacing="0">
                        <tr>
                            <td align="center" width="610">
                                <div align="center" id="map_canvas" style="width: 600px; height: 300px; border-style:solid; border-color:#000000;" border="3" ></div>
                            </td>
                        </tr>
                        <tr>
                        	<td align="right">
                            <a href="/user/location">Location archive...</a>	
                            </td>
                        </tr>
                    </table>
                    
                    <!-- map code ends here -->
                    
            	</td>
          	</tr>
    		<tr>
    			<td colspan="2" align="center">
    				
                    <p class="userTableHeader">Phonecall tracker</p>
                    
                    <?php
						if (count($this->phonecallData)==0)
						{
							echo '<div class="homeNoDataMessage">No data to show</div>';
						}
						else
						{
                    	?>
                            <!-- table for phonecall tracker -->
                            <table border="0" align="center" cellpadding="3" cellspacing="0" class="userTableData">
                                <tr bgcolor="#05DCF3">
                                    <td width="40">Sr.</td>
                                    <td width="100">Dialed/Received</td>
                                    <td width="110">Mobile no </td>
                                    <td width="200">Time</td>
                                </tr>
                                  
                                <?php 
                                    $serial=1;
									$color = array('#B5B5A6','#E1E1E1');
         
                                    for($i=0;$i<count($this->phonecallData);$i++)
                                    {
                                        $pData = $this->phonecallData[$i];
                                        ?>
                                        <tr bgcolor="<?php echo $color[$serial%2]; ?>">
                                            <td><?php echo $serial++."."; ?></td>
                                            <td><?php echo $pData['dialed_or_received']; ?></td>
                                            <td><?php echo $pData['mobile_no']; ?></td>
                                            <td><?php echo $pData['formattedTime']; ?></td>
                                        </tr>
                                    <?php
                                    }
                                    ?>		
                                <tr>
                                    <td colspan="5">
                                        <div align="right"><a href="/user/phonecall">Show all...</a></div>
                                    </td>
                                </tr>
                            </table>
                		<?php
						}
						?>
    			</td>
  			</tr>
  
  			<tr>
    			<td colspan="2" align="center">
    
    				<p class="userTableHeader">Message tracker</p>
      				
                    <?php
						if (count($this->messageData)==0)
						{
							echo '<div class="homeNoDataMessage">No data to show</div>';
						}
						else
						{
						?>	
                            <!-- table for message tracker -->
                            <table border="0" align="center" cellpadding="3" cellspacing="0" class="userTableData">
                                <tr bgcolor="#05DCF3">
                                    <td width="40">Sr.</td>
                                    <td width="100">Sent/Received</td>
                                    <td width="110">Mobile no </td>
                                    <td width="300">Text</td>
                                    <td width="200">Time</td>
                                </tr>
                              
                                <?php 
                                    $serial=1;
									$color = array('#B5B5A6','#E1E1E1');
          
                                    for($i=0;$i<count($this->messageData);$i++)
                                    {
                                        $mData = $this->messageData[$i];
                                        ?>
                                        <tr bgcolor="<?php echo $color[$serial%2]; ?>">
                                            <td><?php echo $serial++."."; ?></td>
                                            <td> 
                                                <?php 
                                                    if ($mData['sent_or_received'])
                                                        echo ("Sent");
                                                    else
                                                        echo ("Received"); 
                                                ?> 
                                            </td>
                                            <td><?php echo $mData['mobile_no']; ?></td>
                                            <td><?php echo $mData['message_data']; ?></td>
                                            <td><?php echo $mData['formattedTime']; ?></td>
                                        </tr>
                                    <?php
                                    }
                                    ?>		
                                <tr>
                                    <td colspan="5">
                                        <div align="right"><a href="/user/message">Show all...</a></div>
                                    </td>
                                </tr>
                            </table>
                        <?php
						}
						?>
    			</td>
  			</tr>
  
  			<tr>
    			<td colspan="2" align="center">
    
    				<p class="userTableHeader">Violation tracker</p>
                    
                    <?php
						if (count($this->violationData)==0)
						{
							echo '<div class="homeNoDataMessage">No data to show</div>';
						}
						else
						{
						?>
        					<!-- table for violation tracker -->
                        	<table border="0" align="center" cellpadding="3" cellspacing="0" class="userTableData">
                                <tr bgcolor="#05DCF3">
                                    <td width="40">Sr.</td>
                                    <td width="400">Violation type </td>
                                    <td width="200"">Time </td>
                                </tr>
          
                                <?php 
                                    $serial=1;
									$color = array('#B5B5A6','#E1E1E1');
            
                                    for($i=0;$i<count($this->violationData);$i++)
                                    {
                                        $vData = $this->violationData[$i];	
                                        ?>
                                        <tr bgcolor="<?php echo $color[$serial%2]; ?>">
                                            <td><?php echo $serial++."."; ?></td>
                                            <td>
                                                <?php
                                                $violation_type =  $vData['violation_type'];
                    
                                                if ($violation_type==1)
                                                    echo ("Trial for closing application");
                                                else if ($violation_type==2)
                                                    echo ("Trial for calling blocked number");
                                                else if ($violation_type==3)
                                                    echo ("Receiving a call from blocked number");
                                                else if ($violation_type==4)
                                                    echo ("Trial for sending a message to blocked number");
                                                else if ($violation_type==5)
                                                    echo ("Receiving a message from blocked number");
                                                else
                                                    echo ("Unknown type violation"); 
                                                ?> 
                                            </td>
                                            <td><?php echo $vData['formattedTime']; ?></td>
                                        </tr>
                                    <?php
                                    }
                                    ?>
                                <tr>
                                    <td colspan="3">
                                        <div align="right"><a href="/user/violation">Show all...</a></div>
                                    </td>
                                </tr>
                            </table>
                        <?php
						}
						?>
            	</td>
            </tr>
        <?php
        }
        ?>

<?php include "media/header_footer_user/footer.phtml"; ?>  