<?php include "media/header_footer_user/header.phtml"; ?>
		  
	<tr>
 	 <td>
    	
        <?php 
			session_start();
			
			if (!isset($_SESSION['child_id']))
			{	
			?>
				<tr>
                    <td colspan="2" align="center" height="20" class="messageSelectChildMessage">
                    	<br>
                        	You must <a href="/user/home">select a child</a> first!	
                    	<br>
                    </td>
                </tr>
			<?php
            }
			else if (count($this->paginator)==0)
			{
			?>
            	<tr>
                    <td colspan="2" align="center" height="20" class="messageNoDataMessage">
                    	<br>
                        	No data to show!	
                    	<br>
                    </td>
                </tr>
            <?php		
			}			
			else if (count($this->paginator)>0)
			{
			?>
				<p class="userTableHeader" align="center">Message tracker :: <?php echo $_SESSION['child_name']; ?></p>
				
                <!-- message data table here -->
                
                <table border="0" align="center" cellpadding="3" cellspacing="0" class="messageTableData">
                  <tr bgcolor="#05DCF3">
                    <td width="40">Sr.</td>
                    <td width="100">Sent/Received</td>
                    <td width="110">Mobile no </td>
                    <td width="300">Text</td>
                    <td width="200">Time</td>
                  </tr>
                  
                  <?php 
                  
                  $serial=1;
                  $color = array('#B5B5A6','#E1E1E1');
                    
                  foreach($this->paginator as $mData)
                  {
                  ?>
                    
                    <tr bgcolor="<?php echo $color[$serial%2]; ?>">
                        <td>
                        <?php echo $serial++."."; ?> 
                        </td>
                        <td> 
                        <?php 
                            if ($mData['sent_or_received'])
                                echo ("Sent");
                            else
                                echo ("Received"); 
                        ?> 
                        </td>
                        <td> 
                        <?php echo $mData['mobile_no']; ?> 
                        </td>
                        <td> 
                        <?php echo $mData['message_data']; ?> 
                        </td>
                        <td> 
                        <?php echo $mData['formattedTime']; ?> 
                        </td>
                    </tr>
                  
                  <?php
                  }
                  
                  ?>
                  
                </table>
                
                <!-- message data table ended -->
      	
				<?php
				echo $this->paginationControl($this->paginator,'Jumping','user/messagepaginationcontrol.phtml');
          	}
			?>
 	  
	  </td>
    </tr>    
        	  
<?php include "media/header_footer_user/footer.phtml"; ?>
		    